[package]
name = "Image_compressor"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.1"
mozjpeg = "0.10.7"
crossbeam-queue = "0.3.11"
rand = "0.9.0"
rayon = "1.5.1"

[dev-dependencies]
colorgrad = "0.7.0"
fs_extra = "1.3.0"
